# Generated by Django 3.0.7 on 2020-06-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('right_of_way', models.TextField(blank=True)),
                ('configuration', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
                ('average_speed', models.IntegerField(default=0)),
                ('padestrians', models.IntegerField(default=0)),
                ('intersection_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_in', to='main_app.Intersection')),
                ('intersection_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_out', to='main_app.Intersection')),
            ],
        ),
    ]
