# Generated by Django 3.0.7 on 2020-06-14 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padestrians', models.IntegerField(default=0)),
                ('cars', models.IntegerField(default=0)),
                ('taxi', models.IntegerField(default=0)),
                ('bus', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='road',
            name='padestrians',
        ),
        migrations.AddField(
            model_name='road',
            name='traffic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Artefact'),
        ),
    ]
