# Generated by Django 3.0.7 on 2020-07-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200716_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intersection',
            name='intersection_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
