# Generated by Django 3.0.7 on 2020-07-27 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200722_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Intersection'),
        ),
    ]
