# Generated by Django 3.0.7 on 2020-07-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_road_network_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='network_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Network'),
        ),
    ]
