# Generated by Django 3.0.7 on 2020-09-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200908_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='road_name',
            field=models.CharField(max_length=50),
        ),
    ]
