# Generated by Django 3.0.7 on 2020-09-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200908_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='num_lanes',
            field=models.IntegerField(default=1),
        ),
    ]
