# Generated by Django 3.0.7 on 2020-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200909_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='intersection_network',
            field=models.FileField(blank=True, null=True, upload_to='config/intersection/network/'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='intersection_nodes',
            field=models.FileField(blank=True, null=True, upload_to='config/intersection/nodes/'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='intersection_simulation',
            field=models.FileField(blank=True, null=True, upload_to='config/intersection/simulation/'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='road_edges',
            field=models.FileField(blank=True, null=True, upload_to='config/intersection/edges/'),
        ),
        migrations.AddField(
            model_name='intersection',
            name='vehicle_routes',
            field=models.FileField(blank=True, null=True, upload_to='config/intersection/routes/'),
        ),
    ]
