# Generated by Django 3.0.7 on 2020-09-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200912_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='rate',
            field=models.IntegerField(default=20),
        ),
    ]
