# Generated by Django 3.0.7 on 2020-09-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_road_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersection',
            name='forecast_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DayForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_0', models.IntegerField(default=317)),
                ('hour_1', models.IntegerField(default=293)),
                ('hour_2', models.IntegerField(default=244)),
                ('hour_3', models.IntegerField(default=292)),
                ('hour_4', models.IntegerField(default=307)),
                ('hour_5', models.IntegerField(default=370)),
                ('hour_6', models.IntegerField(default=270)),
                ('hour_7', models.IntegerField(default=276)),
                ('hour_8', models.IntegerField(default=313)),
                ('hour_9', models.IntegerField(default=191)),
                ('hour_10', models.IntegerField(default=181)),
                ('hour_11', models.IntegerField(default=388)),
                ('hour_12', models.IntegerField(default=154)),
                ('hour_13', models.IntegerField(default=272)),
                ('hour_14', models.IntegerField(default=349)),
                ('hour_15', models.IntegerField(default=361)),
                ('hour_16', models.IntegerField(default=340)),
                ('hour_17', models.IntegerField(default=293)),
                ('hour_18', models.IntegerField(default=362)),
                ('hour_19', models.IntegerField(default=233)),
                ('hour_20', models.IntegerField(default=257)),
                ('hour_21', models.IntegerField(default=231)),
                ('hour_22', models.IntegerField(default=208)),
                ('hour_23', models.IntegerField(default=161)),
                ('road_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Road')),
            ],
        ),
    ]
